### ISSUE TITLE
Usage RTMPLib

### ISSUE THREAD

**Issue by BiIIyTheKid** [fredlllll/RTMPLib#1]
Hi fredlllll,
i want to test some things with rtmp and i found your lib on github. i tried to start a connection like this:
` RTMPConnection rtmp = new RTMPConnection(System.Net.IPAddress.Parse("127.0.0.1"), 1935);`
My question is: Where can i enter the complete RTMP adress like `127.0.0.1/app/streamkey`? 

Thanks for your help!

Regards 
BiIIyTheKid

PS. We could also make a phone call if u would like that. Im from Germany, too :)

**Comment by fredlllll** [comment]
hi, 

sorry to say but i dont think i left the library in a working state. if i recall correctly you have to send a play command with the path app/streamkey. 

if this isnt very urgent, i could try to finish this mess in the coming weeks

i think text is fine for now :P

**Comment by BiIIyTheKid** [comment]
Hi,

thank you very much for your fast reply. I think this is the right approach to send the play command. I studied the specification at this point and i found what you mean.

To run your code, I noticed something in the `Connect()` method inside `TCPClientWithTimeout.cs`: 

I added a return to the if Statement:
`if (Connected == true)`
`{`
              ` // it succeeded`
                `return;`
`}`

Otherwise the else part of the next if statement will be executed. This will noticed the user, that a connection timeout happend.

I also had to connect the internalClient in the `TryConnect` Method to make the code run:
...
`InternalClient = new TcpClient(EndPoint);`
`InternalClient.Connect(EndPoint.Address, EndPoint.Port);`   <--

For my testing scenario im using a nginx server with the rtmp module included (via docker). I can only run this code with my local ip adress within the creation of the RtmpConnection Call. I´ve an external nginx server aswell, but this is not working with your code at the moment. Can you tell me what scenario did you use for your testing?

Thanks for your help!

BiIIyTheKid

**Comment by fredlllll** [comment]
i never got around to test this. the rtmp spec was a mess, and the first time i designed this, i apparently misunderstood the spec, so i had to start over, and apparently i lost interest at some point because i again missed a part of the spec which would require another major refactoring.  so its a miracle this is even working. 

i dont see a reason why it wouldnt work with a remote server, but with a local one. can you look at your traffic with wireshark to see whats happening? thats what i used the first time i had to talk to a rtmp server using the first version of this library

**Comment by fredlllll** [comment]
i think i found the problem with the remote not working

see commit https://github.com/fredlllll/RTMPLib/commit/1b81d58da444eec62d5642901f84e027e20ca055

**Comment by BiIIyTheKid** [comment]
Hi,

i tested your changes right now. AWESOME! Now it runs with external servers too! And another thing is beeing fixed to. I could not receive the S1 message from the service. This runs now aswell!

Thank you very much for your help. Nice work!

**Comment by fredlllll** [comment]
nice to see that it works. i guess i got the simpler things working, i hope it doesnt break in the future
